swagger: '2.0'
info:
  version: 1.0.0
  title: Play Catalog Application
basePath: /api
consumes:
  - application/json
  - application/x-www-form-urlencoded
  - application/xml
  - text/xml
produces:
  - application/json
  - application/xml
  - text/xml
  - application/javascript
  - text/javascript
paths:
  /changes:
    get:
      tags:
        - Play
      summary: Get changes since last synch.
      operationId: getRemoteChanges
      parameters:
      responses:
        '200':
          description: Request was successful
          schema:
            type: array
            items:
              $ref: '#/definitions/Play'
      deprecated: false
      
  /plays:
    post:
      tags:
        - Play
      summary: Create Play.
      operationId: createPlay
      parameters:
        - name: play
          in: body
          description: Play object
          required: true
          schema:
            $ref: '#/definitions/Play'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Play'
      deprecated: false
    
  /plays/{playId}:
    put:
      tags:
        - Play
      summary: Edit Play. 
      operationId: editPlay
      parameters:
        - name: playId
          in: path
          description: Id of Play
          required: true
          type: integer
          format: int64
        - name: play
          in: body
          description: The edited Play object
          required: true
          schema:
            $ref: '#/definitions/Play'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Play'
      deprecated: false
      
    delete:
      tags:
        - Play
      summary: Delete Play.
      operationId: deletePlay
      parameters: 
        - name: playId
          in: path
          description: Play id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Request was successful
      deprecated: false
  
  /games/{orderBy}:
    get:
      tags:
        - Game
      summary: Create Game.
      operationId: createGame
      parameters: 
        - name: orderBy
          in: path
          description: Order logic
          required: true
          type: string
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Game'
      deprecated: false
      
definitions:
  Game:
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      plays:
        type: array
        items:
          $ref: '#/definitions/Play'
    required:
      - id
      - name
    additionalProperties: false
  Play:
    properties:
      id:
        type: integer
        format: int64
      date:
        type: string
        format: date
      quantity:
        type: integer
      game:
        $ref: '#/definitions/Game'
    required: 
      - id
      - date
      - quantity
      - game
    additionalProperties: false
tags:
  - name: Play
  - name: Game
